In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
df=pd.read_csv('supermarket.csv')
df.columns = df.columns.str.replace(' ', '')
df.head()

     CustomerId        Date           Product
0  JKML5ZWXP0XQ  2020-07-20    tropical fruit
1  YOGWQIUPDAJ7  2020-04-30        whole milk
2  Q3NL22281AF6  2020-09-18         pip fruit
3  C59GRTLMZQAU  2020-12-11  other vegetables
4  WUSF8LTEQZ5L  2020-01-02        whole milk

In [3]:
#one
df['Product'].nunique()

137

In [4]:
#Two
df2=df.sort_values(by='Date')

In [5]:
df2['count_pro'] = df2['Product'].str.count(',').add(1).fillna(0) 
df2.head()

         CustomerId        Date                Product  count_pro
27799  KCTZ72QHMDFI  2019-01-01  Instant food products          1
13034  Y0P0N0Q7J20N  2019-01-01    specialty chocolate          1
25842  3K6D758U6XEW  2019-01-01      frozen vegetables          1
8096   4HQQAPAPG6SF  2019-01-01           citrus fruit          1
21803  XF4DEN65CUZO  2019-01-01       other vegetables          1

In [6]:
df2=np.round(df2.groupby(df2['Date'])['count_pro'].sum().mean())
df2

45.0

In [7]:
#Three
total=df['Product'].value_counts()
df3=total.to_frame()
df3.tail(4)

                       Product
bags                         4
baby cosmetics               3
kitchen utensil              1
preservation products        1

In [8]:
#Four
df['Date'] = pd.to_datetime(df['Date'])
df['day_of_week'] = df['Date'].dt.day_name()
df4=df.sort_values(by='CustomerId')
mask=(df['Date']=='2020')
df4=df4.loc[mask]
df4.to_csv('new.csv')
df4=pd.read_csv('new.csv',sep=',')
total=df4['CustomerId'].value_counts()
df4=total.to_frame()
df4.head()

              CustomerId
4YPH390YUX3T           5
2T4TPX1TFIJT           4
K3RBR49WDZGW           4
TYVSUPN2TZOQ           4
7GVEOUTXCERO           3

In [11]:
#Five
total=df.groupby('Date')['day_of_week'].value_counts().sort_values(ascending=False)
df5=total.to_frame()
df5.head(3)

                        day_of_week
Date       day_of_week
2020-01-21 Tuesday               80
2019-08-28 Wednesday             76
2020-03-25 Wednesday             74